version: '3.8'
services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=""
      - JUPYTER_PASSWORD=""

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=master

  hadoop:
    image: sequenceiq/hadoop-docker:latest
    ports:
      - "50070:50070"
    environment:
      - HDFS_USER=root
volumes:
  minio_data:
