version: '3.8'

services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - spark_network

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=master
    networks:
      - spark_network

  hadoop:
    image: sequenceiq/hadoop-docker:latest
    ports:
      - "50070:50070"
    volumes:
      - hadoop_data:/data
    environment:
      - HDFS_USER=root
    networks:
      - spark_network

volumes:
  hadoop_data:

networks:
  spark_network:
    name: spark_network
