version: '3'
services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=master

  hadoop:
    image: sequenceiq/hadoop-docker:latest
    ports:
      - "50070:50070"
    environment:
      - HDFS_USER=root
